CREATE SCHEMA RainbowSchema;
GO

CREATE TABLE RainbowSchema.rainbow (
  HASH NVARCHAR(64) NOT NULL PRIMARY KEY,
  WORD NVARCHAR(128)
);
GO

CREATE CLUSTERED COLUMNSTORE INDEX Columnstoreindex ON RainbowSchema.rainbow;
GO